# Generated by Django 3.2.19 on 2023-12-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cross',
            new_name='Crosses',
        ),
    ]
