# Generated by Django 3.2.19 on 2023-12-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0002_rename_cross_crosses'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosses',
            name='seed_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crosses',
            name='status_text',
            field=models.CharField(default='Made', max_length=10),
        ),
        migrations.AddField(
            model_name='wcp_entries',
            name='genes_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wcp_entries',
            name='notes_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wcp_entries',
            name='purdy_text',
            field=models.CharField(default='Missing', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Families',
            fields=[
                ('family_text', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cross_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross', to='crossing.crosses')),
            ],
        ),
    ]
