# Generated by Django 3.2.19 on 2023-12-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0004_wcp_entries_sample_id_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcp_entries',
            name='genes_text',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wcp_entries',
            name='notes_text',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wcp_entries',
            name='sample_id_text',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
