# Generated by Django 3.2.19 on 2023-12-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0005_auto_20231213_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcp_entries',
            name='eno_text',
            field=models.CharField(max_length=20),
        ),
    ]
