# Generated by Django 3.2.19 on 2023-12-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0006_alter_wcp_entries_eno_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crosses',
            old_name='cross_text',
            new_name='cross_id',
        ),
    ]
