# Generated by Django 3.2.19 on 2023-12-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0007_rename_cross_text_crosses_cross_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcp_entries',
            name='year_text',
            field=models.CharField(max_length=4, verbose_name='Year'),
        ),
    ]
