# Generated by Django 3.2.19 on 2023-12-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0009_auto_20231228_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosses',
            name='cross_date',
            field=models.DateTimeField(verbose_name='Crossing Date'),
        ),
        migrations.AlterField(
            model_name='crosses',
            name='cross_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Cross Id'),
        ),
        migrations.AlterField(
            model_name='crosses',
            name='crosser_text',
            field=models.CharField(max_length=10, verbose_name='Crosser'),
        ),
        migrations.AlterField(
            model_name='crosses',
            name='parent_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_one', to='crossing.wcp_entries', verbose_name='Parent One'),
        ),
        migrations.AlterField(
            model_name='crosses',
            name='parent_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_two', to='crossing.wcp_entries', verbose_name='Parent Two'),
        ),
        migrations.AlterField(
            model_name='crosses',
            name='seed_int',
            field=models.IntegerField(default=0, verbose_name='Seed'),
        ),
        migrations.AlterField(
            model_name='crosses',
            name='status_text',
            field=models.CharField(default='Made', max_length=10, verbose_name='Status'),
        ),
    ]
