# Generated by Django 3.2.19 on 2023-12-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0010_auto_20231229_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='family_text',
        ),
        migrations.AddField(
            model_name='families',
            name='family_id',
            field=models.CharField(default='hey', max_length=200, primary_key=True, serialize=False, verbose_name='Family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='families',
            name='genes_text',
            field=models.CharField(default='hey', max_length=500, verbose_name='Genes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='families',
            name='notes_text',
            field=models.CharField(default='hey', max_length=10000, verbose_name='Notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='families',
            name='purdy_text',
            field=models.CharField(default='hey', max_length=500, verbose_name='Purdy Pedigree'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='families',
            name='cross_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross', to='crossing.crosses', verbose_name='Cross Id'),
        ),
    ]
