# Generated by Django 3.2.19 on 2023-12-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0012_rename_cross_text_families_cross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='families',
            name='genes_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Genes'),
        ),
        migrations.AlterField(
            model_name='families',
            name='notes_text',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Notes'),
        ),
    ]
