# Generated by Django 3.2.19 on 2023-12-30 18:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0014_auto_20231230_1052'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='families',
            managers=[
                ('cur_year_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wcp_entries',
            managers=[
                ('cur_year_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='crosses',
            name='year_text',
            field=models.CharField(default=2024, max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='families',
            name='family_id',
            field=models.CharField(default='placeholder', max_length=200, primary_key=True, serialize=False, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='families',
            name='order_int',
            field=models.IntegerField(default=0, verbose_name='Cross Order'),
        ),
    ]
