# Generated by Django 3.2.19 on 2023-12-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0015_auto_20231230_1330'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='families',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='wcp_entries',
            managers=[
            ],
        ),
    ]
