# Generated by Django 3.2.19 on 2024-01-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0018_wcp_entries_source_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wcp_entries',
            name='eno_text',
        ),
        migrations.AddField(
            model_name='wcp_entries',
            name='eno_int',
            field=models.IntegerField(default=1, verbose_name='Eno'),
            preserve_default=False,
        ),
    ]
