# Generated by Django 3.2.19 on 2024-01-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0019_auto_20240108_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcp_entries',
            name='purdy_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Purdy Pedigree'),
        ),
    ]
