# Generated by Django 3.2.19 on 2024-08-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0021_alter_crosses_status_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosses',
            name='cross_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Crossing Date'),
        ),
        migrations.AlterField(
            model_name='crosses',
            name='crosser_text',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Crosser'),
        ),
    ]
