# Generated by Django 3.2.19 on 2023-12-31 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('plot_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Plot Id')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Stock Id')),
                ('source_plot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='germplasm.plots', verbose_name='Source Plot')),
            ],
        ),
        migrations.AddField(
            model_name='plots',
            name='source_stock',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='germplasm.stocks', verbose_name='Source Stock'),
        ),
        migrations.AddField(
            model_name='plots',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='germplasm.trials', verbose_name='Trial'),
        ),
    ]
