# Generated by Django 3.2.19 on 2023-12-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0002_auto_20231231_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='gen_derived_int',
            field=models.PositiveIntegerField(default=1, verbose_name='Derived Gen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plots',
            name='gen_inbred_int',
            field=models.PositiveIntegerField(default=1, verbose_name='Inbred Gen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='amount_decimal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Seed Amount'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='amount_units',
            field=models.CharField(choices=[('sds', 'Seeds'), ('hds', 'Heads'), ('g', 'Grams'), ('lb', 'Pounds')], default='sds', max_length=3, verbose_name='Seed Units'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='gen_derived_int',
            field=models.PositiveIntegerField(default=1, verbose_name='Derived Gen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='gen_inbred_int',
            field=models.PositiveIntegerField(default=1, verbose_name='Inbred Gen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocks',
            name='location_text',
            field=models.CharField(default='Oz', max_length=200, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
