# Generated by Django 3.2.19 on 2023-12-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0017_alter_wcp_entries_sample_id_text'),
        ('germplasm', '0003_auto_20231231_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='desig_text',
            field=models.CharField(default='bluh', max_length=100, verbose_name='Desig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plots',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crossing.families', verbose_name='Family'),
            preserve_default=False,
        ),
    ]
