# Generated by Django 3.2.19 on 2023-12-31 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0017_alter_wcp_entries_sample_id_text'),
        ('germplasm', '0004_auto_20231231_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='family',
            field=models.ForeignKey(default='bluh', on_delete=django.db.models.deletion.PROTECT, to='crossing.families', verbose_name='Family'),
            preserve_default=False,
        ),
    ]
