# Generated by Django 3.2.19 on 2023-12-31 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0005_stocks_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='source_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='germplasm.stocks', verbose_name='Source Stock'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='source_plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='germplasm.plots', verbose_name='Source Plot'),
        ),
    ]
