# Generated by Django 3.2.19 on 2024-01-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0006_auto_20231231_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='entry_fixed',
            field=models.BooleanField(default=False, verbose_name='Plot Fixed'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='entry_fixed',
            field=models.BooleanField(default=False, verbose_name='Stock Fixed'),
        ),
        migrations.AddField(
            model_name='trials',
            name='plot_type',
            field=models.CharField(choices=[('Yield', 'Yield'), ('HR', 'Headrows'), ('SP', 'Single Plant'), ('Pot', 'Pot')], default='HRs', max_length=10, verbose_name='Plot Type'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('experiment_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Experiment Id')),
                ('status_text', models.CharField(choices=[('Planned', 'Planned'), ('Mapped', 'Mapped'), ('Packed', 'Packed'), ('Planted', 'Planted'), ('Failed', 'Failed'), ('Bags Made', 'Bags Made'), ('Harvested', 'Harvested')], default='Planned', max_length=10, verbose_name='Packing Status')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='germplasm.trials', verbose_name='Trial')),
            ],
        ),
        migrations.AddField(
            model_name='plots',
            name='experiment',
            field=models.ForeignKey(default='dfkd', on_delete=django.db.models.deletion.PROTECT, to='germplasm.experiments', verbose_name='Experiment'),
            preserve_default=False,
        ),
    ]
