# Generated by Django 3.2.19 on 2024-01-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0007_auto_20240101_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plots',
            name='experiment',
        ),
        migrations.AddField(
            model_name='trials',
            name='status_text',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Mapped', 'Mapped'), ('Packed', 'Packed'), ('Planted', 'Planted'), ('Failed', 'Failed'), ('Bags Made', 'Bags Made'), ('Harvested', 'Harvested')], default='Planned', max_length=10, verbose_name='Packing Status'),
        ),
        migrations.DeleteModel(
            name='Experiments',
        ),
    ]
