# Generated by Django 3.2.19 on 2024-01-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0008_auto_20240107_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='notes_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes'),
        ),
    ]
