# Generated by Django 3.2.19 on 2024-01-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0009_plots_notes_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trials',
            name='harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='Harvest Date'),
        ),
        migrations.AddField(
            model_name='trials',
            name='location_text',
            field=models.CharField(default='LAW', max_length=3, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trials',
            name='notes_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='trials',
            name='planting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planting Date'),
        ),
        migrations.AddField(
            model_name='trials',
            name='year_text',
            field=models.CharField(default='2024', max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
