# Generated by Django 3.2.19 on 2024-08-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossing', '0021_alter_crosses_status_text'),
        ('germplasm', '0011_alter_trials_plot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crossing.families', verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='plots',
            name='gen_derived_int',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Derived Gen'),
        ),
        migrations.AlterField(
            model_name='plots',
            name='gen_inbred_int',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Inbred Gen'),
        ),
    ]
