# Generated by Django 3.2.19 on 2024-08-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0012_auto_20240804_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='location_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
