# Generated by Django 3.2.19 on 2025-01-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0014_predictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictions',
            name='prediction_id',
        ),
        migrations.AddField(
            model_name='predictions',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
